Responses = new Meteor.Collection('responses')
Standards = new Meteor.Collection('standards')
Reassessments = new Meteor.Collection('reassessments')
Credits = new Meteor.Collection('credits');
WeinbergCash = new Meteor.Collection('weinbergcash');
systemVariables = new Meteor.Collection('systemVariables');
ReviewPages = new Meteor.Collection('reviewpages');
Links = new Meteor.Collection('standard-links');
Questions = new Meteor.Collection('questions');
Quizzes = new Meteor.Collection('quizzes');
Data = new Meteor.Collection('data');
Variables = new Meteor.Collection(null);
KhanUtil = {};
